# Generated by Django 2.2.1 on 2019-07-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbithole', '0002_auto_20190617_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbithole',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='rabbithole',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rabbithole',
            name='title',
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='category',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='channel_name',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='customUrl',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='sub_category',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='subscribers',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='thumbnail',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='uploads',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='view_count',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
